"""add movimiento_banco, regla_banco, log_procesamiento_banco, asiento origen regla_id

Revision ID: 6b69941fa552
Revises: c2d3e4f5a6b7
Create Date: 2026-10-10 22:15:26.852663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b69941fa552'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regla_banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('patron_regex', sa.String(length=200), nullable=False),
    sa.Column('cuenta_debe', sa.String(length=10), nullable=False),
    sa.Column('cuenta_haber', sa.String(length=10), nullable=False),
    sa.Column('importe_fijo', sa.Numeric(precision=19, scale=2), nullable=True),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('auto_asentar', sa.Boolean(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regla_banco', schema=None) as batch_op:
        batch_op.create_index('ix_regla_banco_empresa_activa', ['empresa_id', 'activa'], unique=False)

    op.create_table('log_procesamiento_banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reglas_aplicadas_json', sa.Text(), nullable=False),
    sa.Column('creados', sa.Integer(), nullable=False),
    sa.Column('pendientes', sa.Integer(), nullable=False),
    sa.Column('fallidos_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_procesamiento_banco', schema=None) as batch_op:
        batch_op.create_index('ix_log_procesamiento_ejercicio_fecha', ['ejercicio_id', 'timestamp'], unique=False)

    op.create_table('movimiento_banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('fecha_operacion', sa.Date(), nullable=False),
    sa.Column('fecha_valor', sa.Date(), nullable=False),
    sa.Column('concepto', sa.String(length=500), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('referencia_2', sa.String(length=100), nullable=True),
    sa.Column('importe', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('divisa', sa.String(length=3), nullable=False),
    sa.Column('codigo_banco', sa.String(length=10), nullable=True),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.Column('info_adicional', sa.String(length=500), nullable=True),
    sa.Column('procesado', sa.Boolean(), nullable=False),
    sa.Column('asiento_id', sa.Integer(), nullable=True),
    sa.Column('regla_id', sa.Integer(), nullable=True),
    sa.Column('hash_unicidad', sa.String(length=64), nullable=False),
    sa.Column('origen_archivo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['asiento_id'], ['asiento.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regla_id'], ['regla_banco.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ejercicio_id', 'hash_unicidad', name='uq_movimiento_banco_ejercicio_hash')
    )
    with op.batch_alter_table('movimiento_banco', schema=None) as batch_op:
        batch_op.create_index('ix_movimiento_banco_ejercicio_fecha_valor', ['ejercicio_id', 'fecha_valor'], unique=False)
        batch_op.create_index('ix_movimiento_banco_ejercicio_procesado', ['ejercicio_id', 'procesado'], unique=False)

    with op.batch_alter_table('apunte', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apunte_asiento_id'))
        batch_op.drop_index(batch_op.f('ix_apunte_cuenta_id'))

    with op.batch_alter_table('asiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origen', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('regla_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_asiento_ejercicio_id_fecha'))
        batch_op.create_foreign_key(None, 'regla_banco', ['regla_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('ejercicio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ejercicio_empresa_id'))

    with op.batch_alter_table('empresausuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresausuario_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_empresausuario_usuario_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresausuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresausuario_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresausuario_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('ejercicio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ejercicio_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('asiento', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_asiento_ejercicio_id_fecha'), ['ejercicio_id', 'fecha'], unique=False)
        batch_op.drop_column('regla_id')
        batch_op.drop_column('origen')

    with op.batch_alter_table('apunte', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apunte_cuenta_id'), ['cuenta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apunte_asiento_id'), ['asiento_id'], unique=False)

    with op.batch_alter_table('movimiento_banco', schema=None) as batch_op:
        batch_op.drop_index('ix_movimiento_banco_ejercicio_procesado')
        batch_op.drop_index('ix_movimiento_banco_ejercicio_fecha_valor')

    op.drop_table('movimiento_banco')
    with op.batch_alter_table('log_procesamiento_banco', schema=None) as batch_op:
        batch_op.drop_index('ix_log_procesamiento_ejercicio_fecha')

    op.drop_table('log_procesamiento_banco')
    with op.batch_alter_table('regla_banco', schema=None) as batch_op:
        batch_op.drop_index('ix_regla_banco_empresa_activa')

    op.drop_table('regla_banco')
    # ### end Alembic commands ###