"""tablas iniciales (identidad y contable)

Revision ID: bb1c920e98ab
Revises: 
Create Date: 2026-10-08 23:10:20.577883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1c920e98ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cif', sa.String(9), nullable=False),
    sa.Column('razon_social', sa.String(120), nullable=False),
    sa.Column('nombre_comercial', sa.String(120), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(50), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rol', sa.String(20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ejercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(20), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'anio', name='uq_ejercicio_empresa_anio')
    )
    op.create_table('empresausuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('rol_especifico', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'empresa_id')
    )
    op.create_table('asiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('concepto', sa.String(300), nullable=False),
    sa.Column('estado', sa.String(20), nullable=False),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicio.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ejercicio_id', 'numero', name='uq_asiento_ejercicio_numero')
    )
    op.create_table('cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(10), nullable=False),
    sa.Column('nombre', sa.String(200), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ejercicio_id', 'codigo', name='uq_cuenta_ejercicio_codigo')
    )
    op.create_table('apunte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asiento_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('debe', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('haber', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['asiento_id'], ['asiento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_empresausuario_usuario_id', 'empresausuario', ['usuario_id'])
    op.create_index('ix_empresausuario_empresa_id', 'empresausuario', ['empresa_id'])
    op.create_index('ix_ejercicio_empresa_id', 'ejercicio', ['empresa_id'])
    op.create_index('ix_asiento_ejercicio_id_fecha', 'asiento', ['ejercicio_id', 'fecha'])
    op.create_index('ix_apunte_asiento_id', 'apunte', ['asiento_id'])
    op.create_index('ix_apunte_cuenta_id', 'apunte', ['cuenta_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apunte_cuenta_id', table_name='apunte')
    op.drop_index('ix_apunte_asiento_id', table_name='apunte')
    op.drop_index('ix_asiento_ejercicio_id_fecha', table_name='asiento')
    op.drop_index('ix_ejercicio_empresa_id', table_name='ejercicio')
    op.drop_index('ix_empresausuario_empresa_id', table_name='empresausuario')
    op.drop_index('ix_empresausuario_usuario_id', table_name='empresausuario')
    op.drop_table('apunte')
    op.drop_table('cuenta')
    op.drop_table('asiento')
    op.drop_table('empresausuario')
    op.drop_table('ejercicio')
    op.drop_table('usuario')
    op.drop_table('empresa')
    # ### end Alembic commands ###
